### PR TITLE
Move android backend to Vulkan.

### LINKED ISSUE #84: Use Vulkan backend on Android devices.
### Describe the proposed feature and its relevance to inferencing

Currently, we have three backend, Metal, Vulkan and VMVX (or cpu). The issue of VMVX is that it is slow from my experience (could be outdated information since the last time I test it is a year ago). Moreover, about 85% of android supports Vulkan, based on the [android developer website](https://developer.android.com/games/develop/vulkan/overview). I believe it would be wise to just let android run on Vulkan.

This doesn't means that we dump everything about VMVX. We could wait for the technology for VMVX to be fast enough to be run on devices. For now, we could introduce CMake build option to force a VMVX backend for people who are opted to try out this widely supported but not too fast backend.

### Context or use case

_No response_

### Proposed solution

Let android's backend to be Vulkan. Introduce CMake build option for force VMVX backend and implement preprocessor directive for it. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RechieKho**
Would fix #84.

### CODE REVIEW

**Comment by RechieKho** [comment]
I hope there is a workflow that bundle up all the build with the samples for testing purposes (like publishing but only for PRs).

**Review by Ughuuu — APPROVED** [review]

**Comment by Ughuuu** [comment]
Sure, we can make it so that we also export samples in a samples directory. The final thing would then be:
```
addons/
            iree.gd..
samples/
            iree.gd..
```
If people want they only install addons, and by default they install samples too.

**Comment by RechieKho** [comment]
Don't merge first! I want to run the CI/CD but there is non after it is approved! Crazy!

**Comment by Ughuuu** [comment]
Don't worry, I'm not gonna merge it, it's ur PR :D

**Comment by fire** [comment]
So close!

Take a look at https://github.com/maiself/godot-python-extension/pull/21

**Comment by RechieKho** [comment]
What a bliss

**Pull request merged**
