### PR TITLE
Use more recent upload-artifact and checkout actions for the GitHub runner.

### PR DESCRIPTION
**Pull request by Ivorforce**
This get rid of most of the [actions warnings](https://github.com/iree-gd/iree.gd/actions/runs/11652267297):

SCR-20241103-orcs

### CODE REVIEW

**Comment by fire** [comment]
@Ughuuu 

Can you help us sign again?

```
Exception: /Users/runner/work/_temp/fbfe7d6b-1f54-4a30-966e-bb88e694c1a1.ps1:42
Line |
  42 |  if (!$CertificateBase64) { throw "No certificate provided" }
     |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No certificate provided
```

**Comment by RechieKho** [comment]
To bundle up a working sample, I turn on codesigning when PR, I guess it only work for people who is in the organization

**Review by fire — APPROVED** [review]
We can yolo (you only live once) merge?

**Comment by Ughuuu** [comment]
The secrets are still in the repo, it should still work. Make another issue to track that signing isnt working if there isnt one already.

**Pull request merged**
