### PR TITLE
Update iree version and make things sync

### PR DESCRIPTION
**Pull request by Ughuuu**
- Update iree version(reason is python iree-compiler i use doesnt have the version used by this repo).
- Remove async mode from this, only support sync mode.
- Use typed array for inputs and outputs
- For macos we use universal libs so use only that.
- Add a model explorer

### CODE REVIEW

**Comment by RechieKho** [comment]
The IREE version is usually the nightly candidates, one would need to use `--find-links` flag to search for nightly release for `iree-compile`. Below is an example for that.
```
python -m pip install \
  --find-links https://iree.dev/pip-release-links.html \
  --upgrade \
  iree-compiler \
  iree-runtime \
  iree-tools-tflite
```

I agree for sync mode and make the user decide it should be async or not with threads.

For typed array, I remember Godot's typed array is only good for export. I had some trouble on appending new value into it although the type matches up. I'll need to research further on this as my understanding might be outdated.

For Mac OS, we are still using universal libs. `sample/addons/iree-gd/iree-gd.gdextesion` includes path to non-universal library to ease my development, `miscellaneous/iree-gd.gdextension` will be used when publish.

By model explorer, you mean checking out the info for the model?

**Comment by Ughuuu** [comment]
This will be the model explorer:
image

It's going to be a tab on the bottom where you can select from a dropdown models(these models will be releases from the iree.zoo repo). The user can click the download button, and then the model will be downloaded into:

`addons/iree-zoo/<model>/`

We will download both the vm.. model and a .gd file with typing info. Will also update readme with this info.

**Comment by fire** [comment]
There's a failing check.

**Comment by Ughuuu** [comment]
Y, the mac sign fails, i need admin access to add some secrets.

**Comment by Ughuuu** [comment]
But impl is not finished anyway, close but not ready. Struggling to do multithreaded stuff in gdscript. After some time i run out of memory. Need to put limits on max threads and max results to store.

**Comment by fire** [comment]
Can the multithreaded stuff be done in a different pr?

**Comment by Ughuuu** [comment]
Hm, maybe, but it depends on how the codegen from zoo will look like and what api it will follow.

**Pull request merged**
